use_frameworks!

target 'QuickApp_Example' do
  pod 'QuickApp', :path => '../'

  target 'QuickApp_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
